# Generated by Django 4.2.2 on 2023-06-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
