# Generated by Django 4.2.2 on 2023-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('data_nascimento_paciente', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf_paciente', models.CharField(max_length=14)),
                ('telefone_celular_paciente', models.CharField(max_length=15)),
            ],
        ),
    ]
