# Generated by Django 4.2.2 on 2023-06-27 14:09

from django.db import migrations, models
import paciente.models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento_paciente',
            field=models.CharField(max_length=10, validators=[paciente.models.validate_date], verbose_name='Data de Nascimento'),
        ),
    ]
